# BetterResidence Configuration
version: "1.0"

# Language setting
# Place language files in lang/ folder (e.g., lang/en-us.yml)
lang: "zh-cn"

# Message Color Theme
# Refer to the theme set in lang/theme.yml
theme: "default"

particle:
  range: 16

claim:
  default-permissions:
    trusted-allow-all: # The key here doesn't matter
      permission: "*:all"
      weight: 900
      value: true
