name: BetterResidence
version: '${version}'
main: cn.jason31416.betterresidence.BetterResidence
api-version: '1.21'
authors: [ Jason31416 ]
softdepend: [ PlaceholderAPI, Vault ]

commands:
  betterresidence:
    description: BetterResidence's main command.
    aliases: [res, betterres, bres]
    usage: /<command>

permissions:
  betterresidence.admin:
    description: Allows using BetterResidence admin commands.
    default: op
